[package]
name = "python_ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }


[lib]
name = "python_ffi"
crate-type = ["cdylib"]


[dependencies.identity]
path = "../../identity"
features = ["dilithium"]