[package]
name = "tls"
version = "0.1.0"
edition = "2021"

[dependencies]
nautilus_core = {path = "../../core"}
negotiation =  {path = "../../protocols/negotiation"}
data_encryption = {path = "../../security/data_encryption"}
async-trait ={version = "0.1.85"}
