[package]
name = "mdns"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bytes = {version = "1.4"}
socket2 = { version = "0.5.8" }
registry = {path = "../../utilities/registry"}