name: Rust

on:
  pull_request:
    paths:
      - "Nautilus/identity/src/**" # Trigger only if changes are in this directory
    branches:
      - "master" # Only for PRs targeting the master branch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Test in Workspace
      run: |
        cd Nautilus/identity
        cargo build --verbose --all-features
        cargo test --verbose --all-features
