name: Rust

on:
  pull_request:
    paths:
      - "Nautilus/identity/src/**" # Trigger only if changes are in this directory
    branches:
      - "master" # Only for PRs targeting the master branch

env:
  CARGO_TERM_COLOR: always

jobs:
  identity-build:
    name: Identity Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build in Workspace
      run: |
        cd Nautilus/identity
        cargo build --verbose --all-features

  identity-test:
    name: Identity Test
    runs-on: ubuntu-latest
    needs: identity-build # Ensure this runs after the build job

    steps:
    - uses: actions/checkout@v4
    - name: Test with Specific Features
      run: |
        cd Nautilus/identity
        cargo test --verbose --features ecdsa,ed25519,secp256k1,dilithium,kyber,falcon
